### ISSUE TITLE
Multiple Clusters with same Name get created once

### ISSUE THREAD

**Issue by automate-this** [h4ndzdatm0ld/nautobot-ssot-vsphere#29]
### Environment
* Python version:  3.9
* Nautobot version:  1.4.5
* nautobot-ssot-vsphere version:  0.1.3

### Expected Behavior
Creating all Clusters

### Observed Behavior
If you have multiple clusters with the same name in vsphere, only one cluster in nautobot gets created and subsequently alle vms are assigned to this one cluster.

### Steps to Reproduce
1. see above
2.
3.

My vSphere looks like this:
+ vSphere-Server
  + My Site 1
    + Prod
  + My Site 2
    + Prod
  + My Site 3
    + Prod

So your plugin should create three cluster groups (My Site 1 to 3) and three clusters (Prod) associated with a cluster group each.
Instead it creates 3 cluster groups, one cluster "prod", associated with cluster group "My Site 3" and adds everything to this cluster.

**Comment by h4ndzdatm0ld** [comment]
Hi @automate-this  Thanks for this feedback. I'll replicate the environment locally and see what I can do! Appreciate you trying the plugin out!

**Comment by h4ndzdatm0ld** [comment]
I think I see the issue here. The `cluster` model in Nautobot is enforced as unique by name. 

https://github.com/nautobot/nautobot/blob/89c443aede427ffae2696b77f41f8b06ceab65fe/nautobot/virtualization/models.py#L136

Perhaps there can be an option for these scenarios / dc&cluster definition in vsphere to create cluster names as {cluster-name}-{cluster-group}. This would not be the default behavior, but could provide a configurable work around for this use-case. Thoughts?

**Comment by h4ndzdatm0ld** [comment]
Looks like it was changed in Nautobot after the fork, I assume. Netbox enforces a unique_together field
https://github.com/netbox-community/netbox/blob/aaf829898b6c4ade5d26fa48d4db1de9c46a87fd/netbox/virtualization/models.py#L160

Anyway, thanks for the feedback. I will raise an issue and see about implementing it. Glad you got it working and all is syncing!
